server:
  # 端口号
  port: 8080
  servlet:
    # 8080后的路径名 http://xxx:8080/listener
    context-path: /listener

# spring config
spring:
  application:
    name: server-listener
  datasource:
    name: listener-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.101.204:3306/test_listerner?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF8
    username: root
    password: ENC(r27PCZ7dxDJzgSk/zamd2KlJ5RGOxgQd8HotERRXnBA=)
#    hikari:
#      # 最小空闲连接
#      minimum-idle: 10
#      # 最大连接数
#      maximum-pool-size: 20
#      # 空闲连接超时时间
#      idle-timeout: 500000
#      # 连接最大存活时间
#      max-lifetime: 540000
#      # 连接超时时间
#      connection-timeout: 60000
  redis:
    host: 47.112.101.204
    port: 6379
    password: ENC(N39ZWiVrwXEfPydon9zJV25JDSa4DZDSkDtBZ7xZ0x4=)
    jedis:
      pool:
        max-active: 20
  # 配置json的全局时间格式
  jackson:
    # 格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 东八区
    time-zone: GMT+8
  # mvc相关
  mvc:
    # 出现找不到处理器错误时候, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    # 不要为工程中的资源文件建立映射(可能会出现如果使用静态资源无法使用的结果, 比如swagger, 需要手动配置)
    add-mappings: false

# mybatis config
mybatis-plus:
  # 映射mapper.xml文件的路径
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    # 开启驼峰命名法
    map-underscore-to-camel-case: true
    # 开启以下配置, 打印mapper的日志, 查看sql语句
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志级别打印
logging:
  level:
    com:
      loiterer:
        listener: debug

# 对配置文件中的信息进行加密操作
# jasypt 密码加密配置
jasypt:
  encryptor:
    # 加密盐值
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    # 加密算法设置 3.0.0 以后
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

loiterer:
  listener:
    # 小程序id
    app-id: ENC(bxzMPtb4ok6vB8Ph5NdLG4sD2QXTPQ/w6KZSTqYwmDw=)
    # 小程序秘钥
    app-secret: ENC(lb5z1nDbTXEiwrQmUSR8R14Sy+g5oJ0JZ87uBFeJK5Wf8o8qyB6js/M/z8E2/i4N)

jwt:
  token:
    secret: ENC(ezkOdz+g5UczfIqAfXSx/P6XO/bIoaePEhkpGTH8siAtb11zH2oEEfJX9IRFM5Km)